### ISSUE TITLE
Does this thing even work?

### ISSUE THREAD

**Issue by wasamasa** [letloop/letloop.cloud#2]
I'm at a loss how to even use it. Even when following the documentation by creating example.scm and using `curl -T example.scm https://letloop.cloud/api/v1 | jq . | tee letloop.cloud.json` to deploy, following the first link gives me error 502 with the default nginx page and following the second link gives me a 404 HTML page with the project logo and "Sorry, object not found." error message.

**Comment by amirouche** [comment]
There is a typo in the README, `hyper` does not take an argument `version`. I pushed a branch at #3 that fix that, and adds more examples.

Let me know if it works for you.

**Comment by amirouche** [comment]
@wasamasa I merged the dev branch, and README is up-to-date.

Thanks for trying.

**Comment by wasamasa** [comment]
Thank you, that example change does indeed help.

I wonder though, where is `hyper` documented? Is it one of your pre-SRFIs?

An error message would have helped figuring this out, but it is a separate issue. For example, if I write Scheme code that does not export a `hyper` procedure, I'd expect more than a 502.

**Comment by amirouche** [comment]
> where is hyper documented? Is it one of your pre-SRFIs?

It is not.

> if I write Scheme code that does not export a hyper procedure, I'd expect more than a 502.

Indeed, I am working on it.
